# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-26 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_auto_20170225_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='finder.Artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='num_of_linked_songs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='artist', chained_model_field='artist', to='finder.Song'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='finder.Artist'),
            preserve_default=False,
        ),
    ]
