# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-26 00:41
from __future__ import unicode_literals

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_auto_20170225_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='album_artist', chained_model_field='artist', to='finder.Song'),
        ),
    ]
