# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-26 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0008_auto_20170225_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='linked_song',
        ),
        migrations.AddField(
            model_name='song',
            name='other_artist_linked_songs',
            field=models.ManyToManyField(blank=True, related_name='_song_other_artist_linked_songs_+', to='finder.Song'),
        ),
        migrations.AddField(
            model_name='song',
            name='same_artist_linked_songs',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='artist', chained_model_field='artist', related_name='_song_same_artist_linked_songs_+', to='finder.Song'),
        ),
    ]
