# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-26 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0009_auto_20170225_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='num_of_linked_songs',
        ),
    ]
