# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-26 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0011_song_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_art_link',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
