# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-26 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0012_album_album_art_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_art_link',
            new_name='album_art',
        ),
    ]
