# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-27 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0015_auto_20170226_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='differentartistvote',
            name='artist_one_song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artist_one_song', to='finder.Song'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='differentartistvote',
            name='artist_two_song',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='artist_two_song', to='finder.Song'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sameartistvote',
            name='artist_song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artist_song', to='finder.Song'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sameartistvote',
            name='related_song',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='related_song', to='finder.Song'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='other_artist_linked_songs',
            field=models.ManyToManyField(blank=True, to='finder.DifferentArtistVote'),
        ),
        migrations.AddField(
            model_name='song',
            name='same_artist_linked_songs',
            field=models.ManyToManyField(blank=True, to='finder.SameArtistVote'),
        ),
    ]
