# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-06 04:36
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0016_auto_20170226_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
